name: Link Checker

on: [push, pull_request]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: lycheeverse/lychee-action@v1.7.0
      with:
        fail: true
