name: Link Checker

on: [push, pull_request]

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: lycheeverse/lychee-action@v1.7.0
    with:
      fail: true
