name: Lint Checker

on: [push, pull_request]

jobs:
  lint-checker:
    runs-on: ubuntu-latest
    steps:
      - name: python-linter
        uses: wemake-services/wemake-python-styleguide
        with:
          path: './src/python'
