name: Lint Checker

on: [push, pull_request]

jobs:
  check-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: wemake-services/wemake-python-styleguide@0.17.0

